# Utiliser une image Python comme base
FROM python:3.11-slim-bookworm

# Installer les dépendances système
RUN apt-get update && apt-get install -y libpq-dev gcc --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers du projet dans le conteneur
COPY . /app

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Définir la commande par défaut pour exécuter votre script `startserver.py`
CMD ["python", "manage.py", "startserver"]